### ISSUE TITLE
Midnight Commander looks very bad

### ISSUE THREAD

**Issue by piotrkasprzyk** [janek-warchol/selenized#7]
When using selenized with Midnight Commander (mc) contrast is very poor, making it almost unusable.
![selenized](https://cloud.githubusercontent.com/assets/14312755/13984916/93bc0e52-f0f9-11e5-9195-24def43a804d.png)

**Comment by janek-warchol** [comment]
Indeed.  I will try to write a skin for mc that changes its background (or you can send me a Pull Request).  In the meantime you can use `mc -b`.

**Comment by janek-warchol** [comment]
@big Just for reference, here's how Midnight Commander looks when you set terminal palette to Selenized medium and use new Selenized skin for mc:
![midnight-commander-selenized-0 5](https://cloud.githubusercontent.com/assets/1368508/14425150/5f01e0e2-ffe5-11e5-8465-108b89bc6009.png)

And here's how it looked by default with xterm palette:
![midnight-commander-xterm](https://cloud.githubusercontent.com/assets/1368508/14425153/630ab240-ffe5-11e5-9712-bee855d43ea6.png)
